### ISSUE TITLE
Review 2 broken links

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-guide#23]
I've added a new workflow that does a bit of proofing for https://guide.ubuntu-mate.org, but won't block publishing if it finds anything wrong.

At the moment, there are currently two dead links:

```
  *  External link http://goinglinux.com/articles/Backups.html failed: 404 No error
  *  External link http://www.dell.com/support/article/us/en/19/how12108/how-to-enable-the-ubuntu-super-key-on-dell-oem-ubuntu-installations?lang=en failed: 403 No error
```

**Comment by goinglinux** [comment]
Hi Luke,

The first dead link is because I redesigned the website. You can replace it
with this one https://goinglinux.com/backup-strategies-for-your-computer/
The second is dead because Dell no longer requires enabling the super key
and has removed the post from their support website. Just remove the text
"Do you need to enable the Super key?" and the paragraph that follows it.

Larry.

**Comment by lah7** [comment]
Thanks Larry. Now to reprint all the books! 😄 📚 🖨️  _I mean, changes applied._
